// Dataset-backed logistic regression for RavenStack subscription upgrade
// prediction. Coefficients are generated by scripts/train-model.mjs from the
// Kaggle CSVs in data/ravenstack, not hand-tuned in this file.

import { FEATURES, MODEL, DEFAULT_INPUT } from './modelArtifact.js'

export { FEATURES, MODEL, DEFAULT_INPUT }

export const INTERCEPT = MODEL.intercept

export function sigmoid(z) {
  return 1 / (1 + Math.exp(-z))
}

export function standardize(feature, value) {
  return ((Number(value) || 0) - feature.mean) / feature.scale
}

export function logit(input) {
  let z = INTERCEPT
  for (const f of FEATURES) {
    z += f.beta * standardize(f, input[f.key])
  }
  return z
}

export function predict(input) {
  const z = logit(input)
  return sigmoid(z)
}

// Per-feature contribution to the log-odds — used for the breakdown chart.
export function contributions(input) {
  return FEATURES.map((f) => {
    const x = Number(input[f.key]) || 0
    const contrib = f.beta * standardize(f, x)
    return {
      key: f.key,
      label: f.label,
      unit: f.unit,
      value: x,
      beta: f.beta,
      contrib,
      sign: contrib >= 0 ? 'pos' : 'neg'
    }
  }).sort((a, b) => Math.abs(b.contrib) - Math.abs(a.contrib))
}

export function classify(p) {
  const { hot, warm, cool } = MODEL.tier_thresholds
  if (p >= hot) return { tier: 'HOT', tone: 'accent', desc: 'TOP 10% SCORE' }
  if (p >= warm) return { tier: 'WARM', tone: 'warning', desc: 'TOP 30% SCORE' }
  if (p >= cool) return { tier: 'COOL', tone: 'neutral', desc: 'MID-RANGE SCORE' }
  return { tier: 'COLD', tone: 'muted', desc: 'LOWER 40% SCORE' }
}
